apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-app
  namespace: flux-system
spec:
  interval: 5m
  path: "clusters/production/apps"
  prune: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-cd
